language: java

os: linux
dist: trusty
jdk: openjdk11

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - ./gradlew build --scan -s

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/